name: Auto Code Fixer

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fix-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff (format and fix)
        run: ruff check . --fix

      - name: Commit and push fixes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: auto-fix code style via Ruff"
          branch: ${{ github.head_ref || github.ref_name }}
