name: Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests if present
        run: |
          if [ -d tests ]; then
            pytest tests/ --maxfail=1 --disable-warnings -q
          else
            echo "No tests directory found, skipping pytest."
          fi